services:
    # Controller
    avdb_datatables.controller:
        class: Avdb\DatatablesBundle\Controller\DataController
        public: true
        arguments:
            - '@avdb_datatables.manager'
            - '@avdb_datatables.factory.response'

    # Factory
    avdb_datatables.factory.response:
        class: Avdb\DatatablesBundle\Factory\ResponseFactory

    # Manager
    avdb_datatables.manager:
        class: Avdb\DatatablesBundle\Manager\DatatableManager

    # Twig
    avdb_datatables.twig_extension:
        class: Avdb\DatatablesBundle\Twig\DatatablesExtension
        arguments:
            - '@translator'
            - '@router'
            - { template: '%avdb_datatables.table_template%' }
        tags:
            - { name: 'twig.extension' }

    # Command
    avdb_datatables.command.generate_tables:
      class: Avdb\DatatablesBundle\Command\GenerateTableCommand
      tags:
        - { name: 'console.command' }